"use client";

import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { getSupabaseBrowserClient } from "@/lib/supabase/browser";

type Asset={id:string;title:string;type:string;status:string;createdAt:string;promptName:string|null;agentName:string|null;creditsCharged:number};type Popular={name:string;count:number};
export default function AdminContent(){const[assets,setAssets]=useState<Asset[]>([]);const[prompts,setPrompts]=useState<Popular[]>([]);const[agents,setAgents]=useState<Popular[]>([]);useEffect(()=>{void(async()=>{const session=await getSupabaseBrowserClient()?.auth.getSession();const response=await fetch("/api/admin/content",{headers:{Authorization:`Bearer ${session?.data.session?.access_token??""}`}});if(response.ok){const body=await response.json();setAssets(body.assets);setPrompts(body.popularPrompts);setAgents(body.popularAgents);}})();},[]);return <main className="mx-auto flex max-w-6xl flex-col gap-6 p-6"><header><p className="text-sm text-muted-foreground">Admin Console</p><h1 className="text-3xl font-semibold">内容资产监控</h1></header><section className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle>热门 Prompt</CardTitle></CardHeader><CardContent className="flex flex-col gap-2 text-sm">{prompts.length?prompts.map(item=><p key={item.name}>{item.name} · {item.count}</p>):<p className="text-muted-foreground">暂无数据</p>}</CardContent></Card><Card><CardHeader><CardTitle>热门 Agent</CardTitle></CardHeader><CardContent className="flex flex-col gap-2 text-sm">{agents.length?agents.map(item=><p key={item.name}>{item.name} · {item.count}</p>):<p className="text-muted-foreground">暂无数据</p>}</CardContent></Card></section><Card><CardHeader><CardTitle>全部内容</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>内容</TableHead><TableHead>类型</TableHead><TableHead>状态</TableHead><TableHead>Prompt</TableHead><TableHead>Agent</TableHead><TableHead>Credits</TableHead><TableHead>时间</TableHead></TableRow></TableHeader><TableBody>{assets.map(asset=><TableRow key={asset.id}><TableCell className="max-w-56 truncate">{asset.title}</TableCell><TableCell>{asset.type}</TableCell><TableCell><Badge variant={asset.status==="completed"?"secondary":"destructive"}>{asset.status}</Badge></TableCell><TableCell>{asset.promptName??"—"}</TableCell><TableCell>{asset.agentName??"默认"}</TableCell><TableCell>{asset.creditsCharged}</TableCell><TableCell>{new Date(asset.createdAt).toLocaleString("zh-CN")}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></main>}
