import { getSupabaseServerClient } from "@/lib/supabase/server";
function store(){const s=getSupabaseServerClient();if(!s)throw new Error("BILLING_UNAVAILABLE");return s}
async function audit(operator:string|undefined,action:string,resourceId:string,metadata:Record<string,unknown>){await store().from("audit_logs").insert({admin_id:operator??null,action,resource_type:"subscription",resource_id:resourceId,metadata})}
export async function getUserSubscription(userId:string){const{data,error}=await store().from("subscriptions").select("*,plans(*)").eq("user_id",userId).eq("status","active").order("created_at",{ascending:false}).maybeSingle();if(error)throw error;return data}
export async function grantSubscriptionCredits(subscriptionId:string){const{data,error}=await store().rpc("grant_subscription_credits",{p_subscription_id:subscriptionId});if(error)throw error;return data}
export async function assignPlan(input:{userId:string;planId:string;operator?:string;expiresAt?:string}){const s=store();const{data,error}=await s.from("subscriptions").insert({user_id:input.userId,plan_id:input.planId,status:"active",expires_at:input.expiresAt??null}).select().single();if(error)throw error;await grantSubscriptionCredits(data.id);await audit(input.operator,"subscription_assigned",data.id,{userId:input.userId,planId:input.planId});return data}
export async function changePlan(input:{subscriptionId:string;planId:string;operator?:string;reason:string}){const s=store();const{data:before}=await s.from("subscriptions").select("*").eq("id",input.subscriptionId).single();const{data,error}=await s.from("subscriptions").update({plan_id:input.planId}).eq("id",input.subscriptionId).select().single();if(error)throw error;await s.from("subscription_adjustments").insert({subscription_id:input.subscriptionId,operator:input.operator??null,reason:input.reason,before_data:before??{},after_data:data});await audit(input.operator,"subscription_changed",input.subscriptionId,{reason:input.reason,before:before,after:data});return data}
export async function listPlans(){const{data,error}=await store().from("plans").select("*").order("created_at");if(error)throw error;return data??[]}
export async function listSubscriptions(){const{data,error}=await store().from("subscriptions").select("*,profiles(email),plans(name)").order("created_at",{ascending:false});if(error)throw error;return data??[]}
export async function createPlan(input:any,operator?:string){const{data,error}=await store().from("plans").insert(input).select().single();if(error)throw error;await audit(operator,"plan_created",data.id,{after:data});return data}
export async function updatePlan(id:string,input:any,operator?:string){const{data,error}=await store().from("plans").update(input).eq("id",id).select().single();if(error)throw error;await audit(operator,"plan_updated",id,{after:data});return data}
export async function disablePlan(id:string,operator?:string){return updatePlan(id,{enabled:false},operator)}
export async function updateSubscription(input:{subscriptionId:string;planId?:string;status?:string;expiresAt?:string;note?:string;operator?:string;reason:string}){const s=store();const{data:before}=await s.from("subscriptions").select("*").eq("id",input.subscriptionId).single();const{data,error}=await s.from("subscriptions").update({...(input.planId?{plan_id:input.planId}:{}),...(input.status?{status:input.status}:{}),...(input.expiresAt?{expires_at:input.expiresAt}:{})}).eq("id",input.subscriptionId).select().single();if(error)throw error;await s.from("subscription_adjustments").insert({subscription_id:input.subscriptionId,operator:input.operator??null,reason:input.note??input.reason,before_data:before??{},after_data:data});await audit(input.operator,"subscription_updated",input.subscriptionId,{reason:input.reason,before,after:data});return data}
