import { getVideoProvider, getVideoProviderName } from "@/lib/ai-providers";
import { getSupabaseServerClient } from "@/lib/supabase/server";

export type VideoStatus = "pending" | "running" | "processing" | "completed" | "failed";
export type VideoTask = { id: string; userId: string; prompt: string; provider: string | null; model: string | null; durationSeconds: number | null; status: VideoStatus; videoUrl: string | null; thumbnailUrl: string | null; metadata: Record<string, unknown>; error: string | null; createdAt: string; updatedAt: string };
type VideoTaskRow = { id: string; user_id: string; prompt: string; provider_name: string | null; model: string | null; duration_seconds: number | null; status: VideoStatus; video_url: string | null; thumbnail_url: string | null; metadata: unknown; error: string | null; created_at: string; updated_at: string };
function asMetadata(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function mapTask(row: VideoTaskRow): VideoTask { return { id: row.id, userId: row.user_id, prompt: row.prompt, provider: row.provider_name, model: row.model, durationSeconds: row.duration_seconds, status: row.status, videoUrl: row.video_url, thumbnailUrl: row.thumbnail_url, metadata: asMetadata(row.metadata), error: row.error, createdAt: row.created_at, updatedAt: row.updated_at }; }
async function requireStore() { const supabase = getSupabaseServerClient(); if (!supabase) throw new Error("VIDEO_TASK_STORE_UNAVAILABLE"); return supabase; }
async function log(level: "info" | "error", event: string, task: VideoTask, metadata: Record<string, unknown>) { const supabase = await requireStore(); await supabase.from("system_logs").insert({ level, event, user_id: task.userId, metadata: { videoTaskId: task.id, ...metadata } }); }

export async function createVideoTask(input: { userId: string; prompt: string; model?: string; durationSeconds?: number }) { const supabase = await requireStore(); const now = new Date().toISOString(); const { data, error } = await supabase.from("video_tasks").insert({ user_id: input.userId, prompt: input.prompt, model: input.model ?? null, duration_seconds: input.durationSeconds ?? 5, status: "pending", created_at: now, updated_at: now }).select().single(); if (error || !data) throw new Error(`Unable to create video task: ${error?.message ?? "unknown error"}`); return mapTask(data as VideoTaskRow); }

async function saveProviderResult(task: VideoTask, result: { status: "processing" | "completed"; provider: string; model: string; videoUrl?: string; thumbnailUrl?: string; metadata?: Record<string, unknown> }) { const supabase = await requireStore(); const status = result.status; const { data, error } = await supabase.from("video_tasks").update({ status, provider_name: result.provider, model: result.model, video_url: result.videoUrl ?? null, thumbnail_url: result.thumbnailUrl ?? null, result: { videoUrl: result.videoUrl ?? null, thumbnailUrl: result.thumbnailUrl ?? null, provider: result.provider, model: result.model }, metadata: result.metadata ?? {}, error: null, updated_at: new Date().toISOString() }).eq("id", task.id).select().single(); if (error || !data) throw new Error(`Unable to save video result: ${error?.message ?? "unknown error"}`); return mapTask(data as VideoTaskRow); }

export async function runVideoTask(taskId: string) { const supabase = await requireStore(); const { data, error } = await supabase.from("video_tasks").select("*").eq("id", taskId).maybeSingle(); if (error || !data) throw new Error("VIDEO_TASK_NOT_FOUND"); const task = mapTask(data as VideoTaskRow); if (task.status === "completed" || task.status === "processing") return task; const provider = getVideoProviderName(); await supabase.from("video_tasks").update({ status: "running", provider_name: provider, error: null, updated_at: new Date().toISOString() }).eq("id", taskId); await log("info", "video_task_started", task, { provider }); try { const result = await getVideoProvider().generateVideo({ taskId: task.id, prompt: task.prompt, model: task.model ?? undefined, durationSeconds: task.durationSeconds ?? undefined }); const saved = await saveProviderResult(task, result); await log("info", saved.status === "completed" ? "video_task_completed" : "video_task_processing", saved, { provider: saved.provider, model: saved.model }); return saved; } catch (exception) { const message = exception instanceof Error ? exception.message : "Video generation failed."; const { data: failed } = await supabase.from("video_tasks").update({ status: "failed", error: message, updated_at: new Date().toISOString() }).eq("id", taskId).select().single(); if (!failed) throw exception; const saved = mapTask(failed as VideoTaskRow); await log("error", "video_task_failed", saved, { provider, error: message }); return saved; } }

export async function refreshVideoTaskStatus(taskId: string) { const supabase = await requireStore(); const { data, error } = await supabase.from("video_tasks").select("*").eq("id", taskId).maybeSingle(); if (error || !data) throw new Error("VIDEO_TASK_NOT_FOUND"); const task = mapTask(data as VideoTaskRow); if (task.status !== "processing") return task; try { const providerStatus = await getVideoProvider().getStatus({ taskId: task.id, providerJobId: typeof task.metadata.providerJobId === "string" ? task.metadata.providerJobId : undefined }); if (providerStatus.status === "failed") throw new Error(providerStatus.error ?? "Video provider failed."); const saved = await saveProviderResult(task, { status: providerStatus.status, provider: task.provider ?? getVideoProviderName(), model: task.model ?? "unknown", videoUrl: providerStatus.videoUrl, thumbnailUrl: providerStatus.thumbnailUrl, metadata: providerStatus.metadata }); if (saved.status === "completed") await log("info", "video_task_completed", saved, { provider: saved.provider, model: saved.model }); return saved; } catch (exception) { const message = exception instanceof Error ? exception.message : "Video status refresh failed."; const { data: failed } = await supabase.from("video_tasks").update({ status: "failed", error: message, updated_at: new Date().toISOString() }).eq("id", task.id).select().single(); if (!failed) throw exception; const saved = mapTask(failed as VideoTaskRow); await log("error", "video_task_failed", saved, { error: message }); return saved; } }

export async function listVideoTasks(userId: string) { const supabase = await requireStore(); const { data, error } = await supabase.from("video_tasks").select("*").eq("user_id", userId).order("updated_at", { ascending: false }); if (error) throw new Error(`Unable to load videos: ${error.message}`); return (data ?? []).map((row) => mapTask(row as VideoTaskRow)); }
export async function getVideoTask(taskId: string, userId?: string) { const supabase = await requireStore(); let query = supabase.from("video_tasks").select("*").eq("id", taskId); if (userId) query = query.eq("user_id", userId); const { data, error } = await query.maybeSingle(); if (error) throw new Error(`Unable to load video task: ${error.message}`); return data ? mapTask(data as VideoTaskRow) : undefined; }
export async function listAllVideoTasks() { const supabase = await requireStore(); const { data, error } = await supabase.from("video_tasks").select("*").order("updated_at", { ascending: false }).limit(100); if (error) throw new Error(`Unable to load video tasks: ${error.message}`); return (data ?? []).map((row) => mapTask(row as VideoTaskRow)); }
