"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { CopyIcon, RefreshCwIcon } from "lucide-react";
import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getSupabaseBrowserClient } from "@/lib/supabase/browser";

type Asset = { id: string; title: string; topic: string; brief: string | null; type: string; status: string; createdAt: string; creditsCharged: number; promptName: string | null; agentName: string | null; content: { script: string | null; storyboard: string[]; raw: Record<string, unknown> }; execution: { workflow: { status: string; currentStep: number; error: string | null } | null; agent: { name: string | null; status: string; error: string | null } | null } };
async function authHeaders(){const session=await getSupabaseBrowserClient()?.auth.getSession();return{Authorization:`Bearer ${session?.data.session?.access_token??""}`};}

export default function ContentDetail(){const{id}=useParams<{id:string}>();const router=useRouter();const[asset,setAsset]=useState<Asset>();const[message,setMessage]=useState("");useEffect(()=>{void(async()=>{const response=await fetch(`/api/content/${id}`,{headers:await authHeaders(),cache:"no-store"});if(response.ok)setAsset((await response.json()).asset);else setMessage("内容不存在或没有访问权限。");})();},[id]);async function regenerate(){const response=await fetch(`/api/tasks/${id}/regenerate`,{method:"POST",headers:await authHeaders()});if(response.ok){const task=(await response.json()).task;router.push(`/dashboard/tasks/${task.id}`);}else setMessage("无法重新生成，请稍后重试。");}if(!asset)return <main className="p-6 text-sm text-muted-foreground">{message||"正在加载内容…"}</main>;return <main className="mx-auto flex max-w-4xl flex-col gap-6 p-6"><header className="flex flex-col gap-3"><Link className="text-sm text-primary" href="/dashboard/content">← 返回内容中心</Link><div className="flex flex-wrap items-center gap-2"><Badge variant="secondary">{asset.type}</Badge><Badge variant="outline">{asset.status}</Badge></div><h1 className="text-3xl font-semibold">{asset.title}</h1><p className="text-sm text-muted-foreground">生成于 {new Date(asset.createdAt).toLocaleString("zh-CN")} · 消耗 {asset.creditsCharged} Credits</p><div className="flex gap-2"><Button variant="outline" onClick={()=>void navigator.clipboard.writeText(asset.content.script??asset.title)}><CopyIcon data-icon="inline-start"/>复制内容</Button><Button onClick={()=>void regenerate()}><RefreshCwIcon data-icon="inline-start"/>重新生成</Button></div></header><Card><CardHeader><CardTitle>生成内容</CardTitle><CardDescription>标题、正文和结构化分镜结果</CardDescription></CardHeader><CardContent className="flex flex-col gap-5"><article className="whitespace-pre-wrap leading-7">{asset.content.script??asset.topic}</article>{asset.content.storyboard.length?<ol className="list-decimal pl-5 leading-7">{asset.content.storyboard.map((scene,index)=><li key={`${index}-${scene}`}>{scene}</li>)}</ol>:null}</CardContent></Card><section className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle>生成参数</CardTitle></CardHeader><CardContent className="flex flex-col gap-2 text-sm"><p>主题：{asset.topic}</p><p>补充：{asset.brief??"—"}</p><p>Prompt：{asset.promptName??"默认 Prompt"}</p><p>Agent：{asset.agentName??"默认工作流"}</p></CardContent></Card><Card><CardHeader><CardTitle>执行流程摘要</CardTitle></CardHeader><CardContent className="flex flex-col gap-2 text-sm"><p>任务：{asset.status}</p><p>Workflow：{asset.execution.workflow?`${asset.execution.workflow.status} · 第 ${asset.execution.workflow.currentStep} 步` : "默认执行"}</p><p>Agent：{asset.execution.agent?`${asset.execution.agent.name??"Agent"} · ${asset.execution.agent.status}`:"未指定"}</p></CardContent></Card></section>{message?<p className="text-sm text-destructive">{message}</p>:null}</main>}
